name: Build README
on:
        push:
        workflow_dispatch:
        schedule:
        - cron: '8,28,48 * * * *'
jobs:
        build:
                runs-on: ubuntu-latest
                steps:
                - name: Check out repo
                  uses: actions/checkout@v2
                - name: Set up python
                  uses: actions/setup-python@v2
                  with:
                        python-version: 3.8
                - name: Install python dependencies
                  run: |
                        python -m pip install feedparser
                - name: Update Readme
                  run: |-
                        python build_readme.py
                        cat README.md
                - name: Commit and push if changed readme
                  run: |-
                        git diff
                        git config --global user.email "readme-bot@example.com"
                        git config --global user.name "README-bot"
                        git diff --quiet || (git add README.md && git commit -m "Updated Readme")
                        git push
